name: Josias Maceda
description: Destinado a apreciadores de um software de qualidade
meta_description: "Blog sobre os mais diversos temas relacionados ao desenvolvimento de software"
email: josiasmaceda@hotmail.com

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: 'https://josiasmaceda.github.io'
google_analytics: 'UA-38707432-2'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://josiasmaceda.com.br'
author:         'Josias Maceda'
